### ISSUE TITLE
Similar Projects

### ISSUE THREAD

**Issue by avit** [mwerner/spigot#1]
I've added a link to Spigot from my [stockboy](https://github.com/avit/stockboy) gem's wiki.

It looks like we have some overlap, and some good ideas individually, and in common. I'd like to draw up a list of key differences so people can choose the best tool for their use case. Would you care to link to my project from your wiki or draw up your own feature comparison?

Let me know what you think. I still need to take a closer look at Spigot, but from my side, constructive feedback is always welcome. :smile:

**Comment by mwerner** [comment]
Thanks for the link, I'll do the same.

From what I can get from stockboy and activewarehouse-etl it looks like you guys are much more on the ETL side of things than spigot is. I'm most interested in a clean DSL and concise implementation in the business layer. Possibly massage the data slightly, but for the most part, just pull in data as provided from the API. The most common use case would be for aggregating similar content (ex: comments) from various social networks, not much ETL happening.

**Comment by avit** [comment]
Gotcha. Yes, stockboy's use case is more batch-oriented data imports from various sources. It straddles the ETL ideas a bit, but not quite. It's more "fetch, transform, funnel", if you will.

>  I'm most interested in a clean DSL and concise implementation in the business layer.

Same here, that's why I thought the projects might be more similar than I thought at first glance. Your resource blocks reminded me of the attribute blocks that I build using instance_eval.

From what I can tell, spigot is better suited for normalizing resource-oriented web services, while stockboy handles garbage from IMAP, FTP, etc. as list-oriented bulk data sets. 

Coincidentally, I just gave a presentation on Stockboy a few weeks ago and the metaphor I used was that consuming APIs is like water from a faucet — but sometimes you have to deal with moving bottled water; that's what stockboy is for.
